fileObj = open('writeTest.txt', 'w', encoding = 'utf-8')
fileObj.write('หนังสือภาษาไพธอนเล่มนี้เหมาะสำหรับผู้เริ่มต้น\n')
fileObj.write('และสนใจในการเขียนโปรแกรม\n')
fileObj.write('โดยไม่จำเป็นต้องมีพื้นฐานมาก่อน')
fileObj.close()
