fileW = open('Unifile.txt', 'w' ,encoding='utf-')
fileW.write('Python programming\n')
fileW.write('การเขียนโปรแกรมภาษาไพธอน\n')
fileW.write('电 脑 编 程')
fileW.close()
fileR = open('Unifile.txt', 'r',encoding='utf-8')
s = fileR.read()
print(s)
fileR.close()
